#ifndef CHENEY_DEF_H
#define CHENEY_DEF_H

#pragma once

#define MESSAGE_HANDLER(method) virtual LRESULT On##method(WPARAM, LPARAM);

#define IMPLEMENT_HANDLER(method , message)\
	LRESULT CheneyWnd::On##method(WPARAM wParam, LPARAM lParam)\
	{\
		return Default(message, wParam, lParam);\
	}\

#define SWITCH_HANDLER(method, message)\
	case message:\
		return On##method(wParam, lParam);\

#define MESSAGE_HANDLERS()\
	MESSAGE_HANDLER(Activate)\
	MESSAGE_HANDLER(ActivateApp)\
	MESSAGE_HANDLER(AskCbFormatName)\
	MESSAGE_HANDLER(CancelMode)\
	MESSAGE_HANDLER(CaptureChanged)\
	MESSAGE_HANDLER(ChangeCbChain)\
	MESSAGE_HANDLER(Char)\
	MESSAGE_HANDLER(CharToItem)\
	MESSAGE_HANDLER(ChildActivate)\
	MESSAGE_HANDLER(Close)\
	MESSAGE_HANDLER(Compacting)\
	MESSAGE_HANDLER(CompareItem)\
	MESSAGE_HANDLER(ContextMenu)\
	MESSAGE_HANDLER(CopyData)\
	MESSAGE_HANDLER(Create)\
	MESSAGE_HANDLER(DeadChar)\
	MESSAGE_HANDLER(DeleteItem)\
	MESSAGE_HANDLER(Destroy)\
	MESSAGE_HANDLER(DestroyClipboard)\
	MESSAGE_HANDLER(DeviceChange)\
	MESSAGE_HANDLER(DevModeChange)\
	MESSAGE_HANDLER(DrawClipboard)\
	MESSAGE_HANDLER(DrawItem)\
	MESSAGE_HANDLER(DropFiles)\
	MESSAGE_HANDLER(Enable)\
	MESSAGE_HANDLER(EndSession)\
	MESSAGE_HANDLER(EnterIdle)\
	MESSAGE_HANDLER(EraseBkgnd)\
	MESSAGE_HANDLER(FontChange)\
	MESSAGE_HANDLER(GetDlgCode)\
	MESSAGE_HANDLER(GetMinMaxInfo)\
	MESSAGE_HANDLER(HelpInfo)\
	MESSAGE_HANDLER(HScroll)\
	MESSAGE_HANDLER(HScrollClipboard)\
	MESSAGE_HANDLER(IconEraseBkgnd)\
	MESSAGE_HANDLER(InitMenu)\
	MESSAGE_HANDLER(InitMenuPopup)\
	MESSAGE_HANDLER(KeyDown)\
	MESSAGE_HANDLER(KeyUp)\
	MESSAGE_HANDLER(KillFocus)\
	MESSAGE_HANDLER(LButtonDblClk)\
	MESSAGE_HANDLER(LButtonDown)\
	MESSAGE_HANDLER(LButtonUp)\
	MESSAGE_HANDLER(MButtonDblClk)\
	MESSAGE_HANDLER(MButtonDown)\
	MESSAGE_HANDLER(MButtonUp)\
	MESSAGE_HANDLER(MDIActivate)\
	MESSAGE_HANDLER(MeasureItem)\
	MESSAGE_HANDLER(MenuChar)\
	MESSAGE_HANDLER(MenuSelect)\
	MESSAGE_HANDLER(MouseActivate)\
	MESSAGE_HANDLER(MouseMove)\
	MESSAGE_HANDLER(MouseWheel)\
	MESSAGE_HANDLER(Move)\
	MESSAGE_HANDLER(Moving)\
	MESSAGE_HANDLER(NcActivate)\
	MESSAGE_HANDLER(NcCalcSize)\
	MESSAGE_HANDLER(NcCreate)\
	MESSAGE_HANDLER(NcDestroy)\
	MESSAGE_HANDLER(NcHitTest)\
	MESSAGE_HANDLER(NcLButtonDblClk)\
	MESSAGE_HANDLER(NcLButtonDown)\
	MESSAGE_HANDLER(NcLButtonUp)\
	MESSAGE_HANDLER(NcMButtonDblClk)\
	MESSAGE_HANDLER(NcMButtonDown)\
	MESSAGE_HANDLER(NcMButtonUp)\
	MESSAGE_HANDLER(NcMouseMove)\
	MESSAGE_HANDLER(NcPaint)\
	MESSAGE_HANDLER(NcRButtonDblClk)\
	MESSAGE_HANDLER(NcRButtonDown)\
	MESSAGE_HANDLER(NcRButtonUp)\
	MESSAGE_HANDLER(Paint)\
	MESSAGE_HANDLER(PaintClipboard)\
	MESSAGE_HANDLER(PaletteChanged)\
	MESSAGE_HANDLER(PaletteIsChanging)\
	MESSAGE_HANDLER(ParentNotify)\
	MESSAGE_HANDLER(QueryDragIcon)\
	MESSAGE_HANDLER(QueryEndSession)\
	MESSAGE_HANDLER(QueryNewPalette)\
	MESSAGE_HANDLER(QueryOpen)\
	MESSAGE_HANDLER(RButtonDblClk)\
	MESSAGE_HANDLER(RButtonDown)\
	MESSAGE_HANDLER(RButtonUp)\
	MESSAGE_HANDLER(RenderAllFormats)\
	MESSAGE_HANDLER(RenderFormat)\
	MESSAGE_HANDLER(SetCursor)\
	MESSAGE_HANDLER(SetFocus)\
	MESSAGE_HANDLER(ShowWindow)\
	MESSAGE_HANDLER(Size)\
	MESSAGE_HANDLER(SizeClipboard)\
	MESSAGE_HANDLER(Sizing)\
	MESSAGE_HANDLER(SpoolerStatus)\
	MESSAGE_HANDLER(StyleChanged)\
	MESSAGE_HANDLER(StyleChanging)\
	MESSAGE_HANDLER(SysChar)\
	MESSAGE_HANDLER(SysColorChange)\
	MESSAGE_HANDLER(SysCommand)\
	MESSAGE_HANDLER(SysDeadChar)\
	MESSAGE_HANDLER(SysKeyDown)\
	MESSAGE_HANDLER(SysKeyUp)\
	MESSAGE_HANDLER(TCard)\
	MESSAGE_HANDLER(TimeChange)\
	MESSAGE_HANDLER(Timer)\
	MESSAGE_HANDLER(VKeyToItem)\
	MESSAGE_HANDLER(VScroll)\
	MESSAGE_HANDLER(VScrollClipboard)\
	MESSAGE_HANDLER(WindowPosChanged)\
	MESSAGE_HANDLER(WindowPosChanging)\
	MESSAGE_HANDLER(WinIniChange)\
	MESSAGE_HANDLER(Command)\
	MESSAGE_HANDLER(Notify)\

#define IMPLEMENT_HANDLERS()\
	IMPLEMENT_HANDLER(Activate, WM_ACTIVATE)\
	IMPLEMENT_HANDLER(ActivateApp, WM_ACTIVATEAPP)\
	IMPLEMENT_HANDLER(AskCbFormatName, WM_ASKCBFORMATNAME)\
	IMPLEMENT_HANDLER(CancelMode, WM_CANCELMODE)\
	IMPLEMENT_HANDLER(CaptureChanged, WM_CAPTURECHANGED)\
	IMPLEMENT_HANDLER(ChangeCbChain, WM_CHANGECBCHAIN)\
	IMPLEMENT_HANDLER(Char, WM_CHAR)\
	IMPLEMENT_HANDLER(CharToItem, WM_CHARTOITEM)\
	IMPLEMENT_HANDLER(ChildActivate, WM_CHILDACTIVATE)\
	IMPLEMENT_HANDLER(Close, WM_CLOSE)\
	IMPLEMENT_HANDLER(Compacting, WM_COMPACTING)\
	IMPLEMENT_HANDLER(CompareItem, WM_COMPAREITEM)\
	IMPLEMENT_HANDLER(ContextMenu, WM_CONTEXTMENU)\
	IMPLEMENT_HANDLER(CopyData, WM_COPYDATA)\
	IMPLEMENT_HANDLER(Create, WM_CREATE)\
	IMPLEMENT_HANDLER(DeadChar, WM_DEADCHAR)\
	IMPLEMENT_HANDLER(DeleteItem, WM_DELETEITEM)\
	IMPLEMENT_HANDLER(Destroy, WM_DESTROY)\
	IMPLEMENT_HANDLER(DestroyClipboard, WM_DESTROYCLIPBOARD)\
	IMPLEMENT_HANDLER(DeviceChange, WM_DEVICECHANGE)\
	IMPLEMENT_HANDLER(DevModeChange, WM_DEVMODECHANGE)\
	IMPLEMENT_HANDLER(DrawClipboard, WM_DRAWCLIPBOARD)\
	IMPLEMENT_HANDLER(DrawItem, WM_DRAWITEM)\
	IMPLEMENT_HANDLER(DropFiles, WM_DROPFILES)\
	IMPLEMENT_HANDLER(Enable, WM_ENABLE)\
	IMPLEMENT_HANDLER(EndSession, WM_ENDSESSION)\
	IMPLEMENT_HANDLER(EnterIdle, WM_ENTERIDLE)\
	IMPLEMENT_HANDLER(EraseBkgnd, WM_ERASEBKGND)\
	IMPLEMENT_HANDLER(FontChange, WM_FONTCHANGE)\
	IMPLEMENT_HANDLER(GetDlgCode, WM_GETDLGCODE)\
	IMPLEMENT_HANDLER(GetMinMaxInfo, WM_GETMINMAXINFO)\
	IMPLEMENT_HANDLER(HelpInfo, WM_HELP)\
	IMPLEMENT_HANDLER(HScroll, WM_HSCROLL)\
	IMPLEMENT_HANDLER(HScrollClipboard, WM_HSCROLLCLIPBOARD)\
	IMPLEMENT_HANDLER(IconEraseBkgnd, WM_ICONERASEBKGND)\
	IMPLEMENT_HANDLER(InitMenu, WM_INITMENU)\
	IMPLEMENT_HANDLER(InitMenuPopup, WM_INITMENUPOPUP)\
	IMPLEMENT_HANDLER(KeyDown, WM_KEYDOWN)\
	IMPLEMENT_HANDLER(KeyUp, WM_KEYUP)\
	IMPLEMENT_HANDLER(KillFocus, WM_KILLFOCUS)\
	IMPLEMENT_HANDLER(LButtonDblClk, WM_LBUTTONDBLCLK)\
	IMPLEMENT_HANDLER(LButtonDown, WM_LBUTTONDOWN)\
	IMPLEMENT_HANDLER(LButtonUp, WM_LBUTTONUP)\
	IMPLEMENT_HANDLER(MButtonDblClk, WM_MBUTTONDBLCLK)\
	IMPLEMENT_HANDLER(MButtonDown, WM_MBUTTONDOWN)\
	IMPLEMENT_HANDLER(MButtonUp, WM_MBUTTONUP)\
	IMPLEMENT_HANDLER(MDIActivate, WM_MDIACTIVATE)\
	IMPLEMENT_HANDLER(MeasureItem, WM_MEASUREITEM)\
	IMPLEMENT_HANDLER(MenuChar, WM_MENUCHAR)\
	IMPLEMENT_HANDLER(MenuSelect, WM_MENUSELECT)\
	IMPLEMENT_HANDLER(MouseActivate, WM_MOUSEACTIVATE)\
	IMPLEMENT_HANDLER(MouseMove, WM_MOUSEMOVE)\
	IMPLEMENT_HANDLER(MouseWheel, WM_MOUSEWHEEL)\
	IMPLEMENT_HANDLER(Move, WM_MOVE)\
	IMPLEMENT_HANDLER(Moving, WM_MOVING)\
	IMPLEMENT_HANDLER(NcActivate, WM_NCACTIVATE)\
	IMPLEMENT_HANDLER(NcCalcSize, WM_NCCALCSIZE)\
	IMPLEMENT_HANDLER(NcCreate, WM_NCCREATE)\
	IMPLEMENT_HANDLER(NcDestroy, WM_NCDESTROY)\
	IMPLEMENT_HANDLER(NcHitTest, WM_NCHITTEST)\
	IMPLEMENT_HANDLER(NcLButtonDblClk, WM_NCLBUTTONDBLCLK)\
	IMPLEMENT_HANDLER(NcLButtonDown, WM_NCLBUTTONDOWN)\
	IMPLEMENT_HANDLER(NcLButtonUp, WM_NCLBUTTONUP)\
	IMPLEMENT_HANDLER(NcMButtonDblClk, WM_NCRBUTTONDBLCLK)\
	IMPLEMENT_HANDLER(NcMButtonDown, WM_NCMBUTTONDOWN)\
	IMPLEMENT_HANDLER(NcMButtonUp, WM_NCMBUTTONUP)\
	IMPLEMENT_HANDLER(NcMouseMove, WM_NCMOUSEMOVE)\
	IMPLEMENT_HANDLER(NcPaint, WM_NCPAINT)\
	IMPLEMENT_HANDLER(NcRButtonDblClk, WM_NCRBUTTONDBLCLK)\
	IMPLEMENT_HANDLER(NcRButtonDown, WM_NCRBUTTONDOWN)\
	IMPLEMENT_HANDLER(NcRButtonUp, WM_NCRBUTTONUP)\
	IMPLEMENT_HANDLER(Paint, WM_PAINT)\
	IMPLEMENT_HANDLER(PaintClipboard, WM_PAINTCLIPBOARD)\
	IMPLEMENT_HANDLER(PaletteChanged, WM_PALETTECHANGED)\
	IMPLEMENT_HANDLER(PaletteIsChanging, WM_PALETTEISCHANGING)\
	IMPLEMENT_HANDLER(ParentNotify, WM_PARENTNOTIFY)\
	IMPLEMENT_HANDLER(QueryDragIcon, WM_QUERYDRAGICON)\
	IMPLEMENT_HANDLER(QueryEndSession, WM_QUERYENDSESSION)\
	IMPLEMENT_HANDLER(QueryNewPalette, WM_QUERYNEWPALETTE)\
	IMPLEMENT_HANDLER(QueryOpen, WM_QUERYOPEN)\
	IMPLEMENT_HANDLER(RButtonDblClk, WM_RBUTTONDBLCLK)\
	IMPLEMENT_HANDLER(RButtonDown, WM_RBUTTONDOWN)\
	IMPLEMENT_HANDLER(RButtonUp, WM_RBUTTONUP)\
	IMPLEMENT_HANDLER(RenderAllFormats, WM_RENDERALLFORMATS)\
	IMPLEMENT_HANDLER(RenderFormat, WM_RENDERFORMAT)\
	IMPLEMENT_HANDLER(SetCursor, WM_SETCURSOR)\
	IMPLEMENT_HANDLER(SetFocus, WM_SETFOCUS)\
	IMPLEMENT_HANDLER(ShowWindow, WM_SHOWWINDOW)\
	IMPLEMENT_HANDLER(Size, WM_SIZE)\
	IMPLEMENT_HANDLER(SizeClipboard, WM_SIZECLIPBOARD)\
	IMPLEMENT_HANDLER(Sizing, WM_SIZING)\
	IMPLEMENT_HANDLER(SpoolerStatus, WM_SPOOLERSTATUS)\
	IMPLEMENT_HANDLER(StyleChanged, WM_STYLECHANGED)\
	IMPLEMENT_HANDLER(StyleChanging, WM_STYLECHANGING)\
	IMPLEMENT_HANDLER(SysChar, WM_SYSCHAR)\
	IMPLEMENT_HANDLER(SysColorChange, WM_SYSCOLORCHANGE)\
	IMPLEMENT_HANDLER(SysCommand, WM_SYSCOMMAND)\
	IMPLEMENT_HANDLER(SysDeadChar, WM_DEADCHAR)\
	IMPLEMENT_HANDLER(SysKeyDown, WM_SYSKEYDOWN)\
	IMPLEMENT_HANDLER(SysKeyUp, WM_SYSKEYUP)\
	IMPLEMENT_HANDLER(TCard, WM_TCARD)\
	IMPLEMENT_HANDLER(TimeChange, WM_TIMECHANGE)\
	IMPLEMENT_HANDLER(Timer, WM_TIMECHANGE)\
	IMPLEMENT_HANDLER(VKeyToItem, WM_VKEYTOITEM)\
	IMPLEMENT_HANDLER(VScroll, WM_VSCROLL)\
	IMPLEMENT_HANDLER(VScrollClipboard, WM_VSCROLLCLIPBOARD)\
	IMPLEMENT_HANDLER(WindowPosChanged, WM_WINDOWPOSCHANGED)\
	IMPLEMENT_HANDLER(WindowPosChanging, WM_WINDOWPOSCHANGING)\
	IMPLEMENT_HANDLER(WinIniChange, WM_WININICHANGE)\
	IMPLEMENT_HANDLER(Command, WM_COMMAND)\
	IMPLEMENT_HANDLER(Notify, WM_NOTIFY)\

#define SWITCH_HANDLERS()\
	SWITCH_HANDLER(Activate, WM_ACTIVATE)\
	SWITCH_HANDLER(ActivateApp, WM_ACTIVATEAPP)\
	SWITCH_HANDLER(AskCbFormatName, WM_ASKCBFORMATNAME)\
	SWITCH_HANDLER(CancelMode, WM_CANCELMODE)\
	SWITCH_HANDLER(CaptureChanged, WM_CAPTURECHANGED)\
	SWITCH_HANDLER(ChangeCbChain, WM_CHANGECBCHAIN)\
	SWITCH_HANDLER(Char, WM_CHAR)\
	SWITCH_HANDLER(CharToItem, WM_CHARTOITEM)\
	SWITCH_HANDLER(ChildActivate, WM_CHILDACTIVATE)\
	SWITCH_HANDLER(Close, WM_CLOSE)\
	SWITCH_HANDLER(Compacting, WM_COMPACTING)\
	SWITCH_HANDLER(CompareItem, WM_COMPAREITEM)\
	SWITCH_HANDLER(ContextMenu, WM_CONTEXTMENU)\
	SWITCH_HANDLER(CopyData, WM_COPYDATA)\
	SWITCH_HANDLER(Create, WM_CREATE)\
	SWITCH_HANDLER(DeadChar, WM_DEADCHAR)\
	SWITCH_HANDLER(DeleteItem, WM_DELETEITEM)\
	SWITCH_HANDLER(Destroy, WM_DESTROY)\
	SWITCH_HANDLER(DestroyClipboard, WM_DESTROYCLIPBOARD)\
	SWITCH_HANDLER(DeviceChange, WM_DEVICECHANGE)\
	SWITCH_HANDLER(DevModeChange, WM_DEVMODECHANGE)\
	SWITCH_HANDLER(DrawClipboard, WM_DRAWCLIPBOARD)\
	SWITCH_HANDLER(DrawItem, WM_DRAWITEM)\
	SWITCH_HANDLER(DropFiles, WM_DROPFILES)\
	SWITCH_HANDLER(Enable, WM_ENABLE)\
	SWITCH_HANDLER(EndSession, WM_ENDSESSION)\
	SWITCH_HANDLER(EnterIdle, WM_ENTERIDLE)\
	SWITCH_HANDLER(EraseBkgnd, WM_ERASEBKGND)\
	SWITCH_HANDLER(FontChange, WM_FONTCHANGE)\
	SWITCH_HANDLER(GetDlgCode, WM_GETDLGCODE)\
	SWITCH_HANDLER(GetMinMaxInfo, WM_GETMINMAXINFO)\
	SWITCH_HANDLER(HelpInfo, WM_HELP)\
	SWITCH_HANDLER(HScroll, WM_HSCROLL)\
	SWITCH_HANDLER(HScrollClipboard, WM_HSCROLLCLIPBOARD)\
	SWITCH_HANDLER(IconEraseBkgnd, WM_ICONERASEBKGND)\
	SWITCH_HANDLER(InitMenu, WM_INITMENU)\
	SWITCH_HANDLER(InitMenuPopup, WM_INITMENUPOPUP)\
	SWITCH_HANDLER(KeyDown, WM_KEYDOWN)\
	SWITCH_HANDLER(KeyUp, WM_KEYUP)\
	SWITCH_HANDLER(KillFocus, WM_KILLFOCUS)\
	SWITCH_HANDLER(LButtonDblClk, WM_LBUTTONDBLCLK)\
	SWITCH_HANDLER(LButtonDown, WM_LBUTTONDOWN)\
	SWITCH_HANDLER(LButtonUp, WM_LBUTTONUP)\
	SWITCH_HANDLER(MButtonDblClk, WM_MBUTTONDBLCLK)\
	SWITCH_HANDLER(MButtonDown, WM_MBUTTONDOWN)\
	SWITCH_HANDLER(MButtonUp, WM_MBUTTONUP)\
	SWITCH_HANDLER(MDIActivate, WM_MDIACTIVATE)\
	SWITCH_HANDLER(MeasureItem, WM_MEASUREITEM)\
	SWITCH_HANDLER(MenuChar, WM_MENUCHAR)\
	SWITCH_HANDLER(MenuSelect, WM_MENUSELECT)\
	SWITCH_HANDLER(MouseActivate, WM_MOUSEACTIVATE)\
	SWITCH_HANDLER(MouseMove, WM_MOUSEMOVE)\
	SWITCH_HANDLER(MouseWheel, WM_MOUSEWHEEL)\
	SWITCH_HANDLER(Move, WM_MOVE)\
	SWITCH_HANDLER(Moving, WM_MOVING)\
	SWITCH_HANDLER(NcActivate, WM_NCACTIVATE)\
	SWITCH_HANDLER(NcCalcSize, WM_NCCALCSIZE)\
	SWITCH_HANDLER(NcCreate, WM_NCCREATE)\
	SWITCH_HANDLER(NcDestroy, WM_NCDESTROY)\
	SWITCH_HANDLER(NcHitTest, WM_NCHITTEST)\
	SWITCH_HANDLER(NcLButtonDblClk, WM_NCLBUTTONDBLCLK)\
	SWITCH_HANDLER(NcLButtonDown, WM_NCLBUTTONDOWN)\
	SWITCH_HANDLER(NcLButtonUp, WM_NCLBUTTONUP)\
	SWITCH_HANDLER(NcMButtonDblClk, WM_NCMBUTTONDBLCLK)\
	SWITCH_HANDLER(NcMButtonDown, WM_NCMBUTTONDOWN)\
	SWITCH_HANDLER(NcMButtonUp, WM_NCMBUTTONUP)\
	SWITCH_HANDLER(NcMouseMove, WM_NCMOUSEMOVE)\
	SWITCH_HANDLER(NcPaint, WM_NCPAINT)\
	SWITCH_HANDLER(NcRButtonDblClk, WM_NCRBUTTONDBLCLK)\
	SWITCH_HANDLER(NcRButtonDown, WM_NCRBUTTONDOWN)\
	SWITCH_HANDLER(NcRButtonUp, WM_NCRBUTTONUP)\
	SWITCH_HANDLER(Paint, WM_PAINT)\
	SWITCH_HANDLER(PaintClipboard, WM_PAINTCLIPBOARD)\
	SWITCH_HANDLER(PaletteChanged, WM_PALETTECHANGED)\
	SWITCH_HANDLER(PaletteIsChanging, WM_PALETTEISCHANGING)\
	SWITCH_HANDLER(ParentNotify, WM_PARENTNOTIFY)\
	SWITCH_HANDLER(QueryDragIcon, WM_QUERYDRAGICON)\
	SWITCH_HANDLER(QueryEndSession, WM_QUERYENDSESSION)\
	SWITCH_HANDLER(QueryNewPalette, WM_QUERYNEWPALETTE)\
	SWITCH_HANDLER(QueryOpen, WM_QUERYOPEN)\
	SWITCH_HANDLER(RButtonDblClk, WM_RBUTTONDBLCLK)\
	SWITCH_HANDLER(RButtonDown, WM_RBUTTONDOWN)\
	SWITCH_HANDLER(RButtonUp, WM_RBUTTONUP)\
	SWITCH_HANDLER(RenderAllFormats, WM_RENDERALLFORMATS)\
	SWITCH_HANDLER(RenderFormat, WM_RENDERFORMAT)\
	SWITCH_HANDLER(SetCursor, WM_SETCURSOR)\
	SWITCH_HANDLER(SetFocus, WM_SETFOCUS)\
	SWITCH_HANDLER(ShowWindow, WM_SHOWWINDOW)\
	SWITCH_HANDLER(Size, WM_SIZE)\
	SWITCH_HANDLER(SizeClipboard, WM_SIZECLIPBOARD)\
	SWITCH_HANDLER(Sizing, WM_SIZING)\
	SWITCH_HANDLER(SpoolerStatus, WM_SPOOLERSTATUS)\
	SWITCH_HANDLER(StyleChanged, WM_STYLECHANGED)\
	SWITCH_HANDLER(StyleChanging, WM_STYLECHANGING)\
	SWITCH_HANDLER(SysChar, WM_SYSCHAR)\
	SWITCH_HANDLER(SysColorChange, WM_SYSCOLORCHANGE)\
	SWITCH_HANDLER(SysCommand, WM_SYSCOMMAND)\
	SWITCH_HANDLER(SysDeadChar, WM_SYSDEADCHAR)\
	SWITCH_HANDLER(SysKeyDown, WM_SYSKEYDOWN)\
	SWITCH_HANDLER(SysKeyUp, WM_SYSKEYUP)\
	SWITCH_HANDLER(TCard, WM_TCARD)\
	SWITCH_HANDLER(TimeChange, WM_TIMECHANGE)\
	SWITCH_HANDLER(Timer, WM_TIMER)\
	SWITCH_HANDLER(VKeyToItem, WM_VKEYTOITEM)\
	SWITCH_HANDLER(VScroll, WM_VSCROLL)\
	SWITCH_HANDLER(VScrollClipboard, WM_VSCROLLCLIPBOARD)\
	SWITCH_HANDLER(WindowPosChanged, WM_WINDOWPOSCHANGED)\
	SWITCH_HANDLER(WindowPosChanging, WM_WINDOWPOSCHANGING)\
	SWITCH_HANDLER(WinIniChange, WM_WININICHANGE)\
	SWITCH_HANDLER(Command, WM_COMMAND)\
	SWITCH_HANDLER(Notify, WM_NOTIFY)\

#endif
